import {
	BloodType,
	EmployeeStatus,
	EmployeeType,
	Gender,
	MaritalStatus,
	Prisma,
	PrismaClient,
	WorkScheduleType,
} from "@prisma/client";

const EMPLOYEE_ID_PREFIXES = {
	MILITARY: "FPC",
	CIVILIAN: "FPCIV",
	TEMPORARY: "TMP",
} as const;

interface BaseEmployeeData {
	firstName: string;
	firstNameAm: string;
	middleName: string;
	middleNameAm: string;
	lastName: string;
	lastNameAm: string;
	gender: Gender;
	dateOfBirth: Date;
	birthPlace: string;
	birthPlaceAm: string;
	height: number;
	weight: number;
	bloodType: BloodType;
	eyeColor: string;
	hairColor: string;
	distinguishingMarks?: string;
	ethnicity: string;
	faydaId?: string;
	passportNumber?: string;
	drivingLicense?: string;
	primaryPhone: string;
	secondaryPhone?: string;
	email?: string;
	employeeType: EmployeeType;
	employmentDate: Date;
	centerCode: string;
	departmentCode: string;
	positionCode: string;
	rankCode?: string;
	currentSalaryStep?: number;
	currentSalary?: number;
	maritalStatus: MaritalStatus;
	marriageDate?: Date;
	workScheduleType: WorkScheduleType;
	contractStartDate?: Date;
	contractEndDate?: Date;
	contractAmount?: number;
	addressSubCityCode: string;
	addressWoredaCode: string;
	houseNumber?: string;
	uniqueAreaName?: string;
	motherFullName: string;
	motherFullNameAm: string;
	motherPhone?: string;
	motherIsAlive: boolean;
	motherAddress?: string;
	emergencyFullName: string;
	emergencyFullNameAm: string;
	emergencyRelationship: string;
	emergencyPhone: string;
	emergencyAltPhone?: string;
	isTransfer?: boolean;
	sourceOrganization?: string;
	originalEmploymentDate?: Date;
}

const EMPLOYEES_DATA: BaseEmployeeData[] = [
	{
		firstName: "Abebe",
		firstNameAm: "አበበ",
		middleName: "Kebede",
		middleNameAm: "ከበደ",
		lastName: "Tadesse",
		lastNameAm: "ታደሰ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1985-03-15"),
		birthPlace: "Addis Ababa",
		birthPlaceAm: "አዲስ አበባ",
		height: 175,
		weight: 78,
		bloodType: BloodType.O_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Amhara",
		faydaId: "ETH-1234567890",
		drivingLicense: "AA-1234567",
		primaryPhone: "+251911234501",
		secondaryPhone: "+251922345601",
		email: "abebe.kebede@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2010-01-15"),
		centerCode: "HQ",
		departmentCode: "ADM",
		positionCode: "DIR",
		rankCode: "COL",
		currentSalaryStep: 5,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2012-06-15"),
		workScheduleType: WorkScheduleType.REGULAR,
		isTransfer: true,
		sourceOrganization: "Ethiopian National Defense Force",
		originalEmploymentDate: new Date("2005-06-01"),
		addressSubCityCode: "LD",
		addressWoredaCode: "LD01",
		houseNumber: "123",
		uniqueAreaName: "Mexico Area",
		motherFullName: "Almaz Worku Desta",
		motherFullNameAm: "አልማዝ ወርቁ ደስታ",
		motherPhone: "+251911111101",
		motherIsAlive: true,
		motherAddress: "Addis Ababa, Kirkos",
		emergencyFullName: "Tigist Haile Mengistu",
		emergencyFullNameAm: "ትግስት ኃይሌ መንግስቱ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222201",
		emergencyAltPhone: "+251933333301",
	},
	{
		firstName: "Tigist",
		firstNameAm: "ትግስት",
		middleName: "Haile",
		middleNameAm: "ኃይሌ",
		lastName: "Gebremariam",
		lastNameAm: "ገብረማሪያም",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1988-07-22"),
		birthPlace: "Mekelle",
		birthPlaceAm: "መቀሌ",
		height: 165,
		weight: 62,
		bloodType: BloodType.A_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Tigray",
		faydaId: "ETH-2345678901",
		primaryPhone: "+251911234502",
		email: "tigist.haile@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2012-03-01"),
		centerCode: "HQ",
		departmentCode: "HR",
		positionCode: "DHEAD",
		rankCode: "LTCOL",
		currentSalaryStep: 4,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "BO",
		addressWoredaCode: "BO01",
		houseNumber: "456",
		uniqueAreaName: "Bole Medhanialem",
		motherFullName: "Hana Gebre Kidane",
		motherFullNameAm: "ሀና ገብረ ኪዳን",
		motherPhone: "+251911111102",
		motherIsAlive: true,
		emergencyFullName: "Haile Gebremariam Kidane",
		emergencyFullNameAm: "ኃይሌ ገብረማሪያም ኪዳን",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222202",
	},
	{
		firstName: "Tesfaye",
		firstNameAm: "ተስፋዬ",
		middleName: "Worku",
		middleNameAm: "ወርቁ",
		lastName: "Demissie",
		lastNameAm: "ደምሴ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1980-11-08"),
		birthPlace: "Bahir Dar",
		birthPlaceAm: "ባህር ዳር",
		height: 180,
		weight: 85,
		bloodType: BloodType.B_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		distinguishingMarks: "Scar on left eyebrow",
		ethnicity: "Amhara",
		faydaId: "ETH-3456789012",
		drivingLicense: "AA-2345678",
		primaryPhone: "+251911234503",
		email: "tesfaye.worku@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2005-06-20"),
		centerCode: "KLT",
		departmentCode: "SEC",
		positionCode: "DIR",
		rankCode: "COL",
		currentSalaryStep: 7,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2008-09-20"),
		workScheduleType: WorkScheduleType.SHIFT_24,
		isTransfer: true,
		sourceOrganization: "Federal Police Commission",
		originalEmploymentDate: new Date("2000-03-15"),
		addressSubCityCode: "AK",
		addressWoredaCode: "AK01",
		houseNumber: "789",
		uniqueAreaName: "Kaliti Industrial",
		motherFullName: "Birke Tadesse Alemu",
		motherFullNameAm: "ብርኬ ታደሰ አለሙ",
		motherPhone: "+251911111103",
		motherIsAlive: true,
		emergencyFullName: "Marta Worku Alemu",
		emergencyFullNameAm: "ማርታ ወርቁ አለሙ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222203",
	},
	{
		firstName: "Meron",
		firstNameAm: "ሜሮን",
		middleName: "Assefa",
		middleNameAm: "አሰፋ",
		lastName: "Bekele",
		lastNameAm: "በቀለ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1990-04-12"),
		birthPlace: "Hawassa",
		birthPlaceAm: "ሀዋሳ",
		height: 160,
		weight: 55,
		bloodType: BloodType.AB_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Sidama",
		faydaId: "ETH-4567890123",
		primaryPhone: "+251911234504",
		email: "meron.assefa@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2015-09-10"),
		centerCode: "KLT",
		departmentCode: "HR",
		positionCode: "HRSP",
		rankCode: "CPT",
		currentSalaryStep: 3,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "AK",
		addressWoredaCode: "AK02",
		houseNumber: "321",
		motherFullName: "Meseret Desta Haile",
		motherFullNameAm: "መሰረት ደስታ ኃይሌ",
		motherPhone: "+251911111104",
		motherIsAlive: true,
		emergencyFullName: "Assefa Bekele Tadesse",
		emergencyFullNameAm: "አሰፋ በቀለ ታደሰ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222204",
	},
	{
		firstName: "Dawit",
		firstNameAm: "ዳዊት",
		middleName: "Gebre",
		middleNameAm: "ገብረ",
		lastName: "Haileselassie",
		lastNameAm: "ኃይለሥላሴ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1987-09-25"),
		birthPlace: "Dire Dawa",
		birthPlaceAm: "ድሬ ዳዋ",
		height: 178,
		weight: 80,
		bloodType: BloodType.O_NEGATIVE,
		eyeColor: "Dark Brown",
		hairColor: "Black",
		ethnicity: "Oromo",
		faydaId: "ETH-5678901234",
		drivingLicense: "DD-1234567",
		primaryPhone: "+251911234505",
		email: "dawit.gebre@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2011-02-14"),
		centerCode: "ZWY",
		departmentCode: "SEC",
		positionCode: "DIR",
		rankCode: "LTCOL",
		currentSalaryStep: 5,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2014-01-25"),
		workScheduleType: WorkScheduleType.SHIFT_24,
		isTransfer: true,
		sourceOrganization: "Oromia Regional Police",
		originalEmploymentDate: new Date("2006-09-10"),
		addressSubCityCode: "YK",
		addressWoredaCode: "YK01",
		houseNumber: "567",
		uniqueAreaName: "Yeka Abado",
		motherFullName: "Sara Mekonnen Haile",
		motherFullNameAm: "ሳራ መኮንን ኃይሌ",
		motherPhone: "+251911111105",
		motherIsAlive: true,
		emergencyFullName: "Helen Gebre Mekonnen",
		emergencyFullNameAm: "ሄለን ገብረ መኮንን",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222205",
	},
	{
		firstName: "Hanna",
		firstNameAm: "ሀና",
		middleName: "Desta",
		middleNameAm: "ደስታ",
		lastName: "Wolde",
		lastNameAm: "ወልደ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1992-01-30"),
		birthPlace: "Gondar",
		birthPlaceAm: "ጎንደር",
		height: 162,
		weight: 58,
		bloodType: BloodType.A_NEGATIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Amhara",
		faydaId: "ETH-6789012345",
		primaryPhone: "+251911234506",
		email: "hanna.desta@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2016-11-05"),
		centerCode: "ZWY",
		departmentCode: "HR",
		positionCode: "HRSP",
		rankCode: "1LT",
		currentSalaryStep: 2,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "GU",
		addressWoredaCode: "GU01",
		houseNumber: "234",
		motherFullName: "Rahel Tadesse Gebre",
		motherFullNameAm: "ራሄል ታደሰ ገብረ",
		motherPhone: "+251911111106",
		motherIsAlive: true,
		emergencyFullName: "Desta Wolde Kidane",
		emergencyFullNameAm: "ደስታ ወልደ ኪዳን",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222206",
	},
	{
		firstName: "Solomon",
		firstNameAm: "ሰለሞን",
		middleName: "Mekonnen",
		middleNameAm: "መኮንን",
		lastName: "Asefa",
		lastNameAm: "አሰፋ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1983-06-18"),
		birthPlace: "Jimma",
		birthPlaceAm: "ጅማ",
		height: 182,
		weight: 88,
		bloodType: BloodType.B_NEGATIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		distinguishingMarks: "Mole on right cheek",
		ethnicity: "Oromo",
		faydaId: "ETH-7890123456",
		drivingLicense: "OR-1234567",
		primaryPhone: "+251911234507",
		email: "solomon.mekonnen@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2008-04-22"),
		centerCode: "DRD",
		departmentCode: "SEC",
		positionCode: "DIR",
		rankCode: "COL",
		currentSalaryStep: 6,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2010-12-10"),
		workScheduleType: WorkScheduleType.SHIFT_24,
		isTransfer: true,
		sourceOrganization: "Amhara Regional Police",
		originalEmploymentDate: new Date("2003-01-20"),
		addressSubCityCode: "KI",
		addressWoredaCode: "KI01",
		houseNumber: "890",
		motherFullName: "Kidist Haile Worku",
		motherFullNameAm: "ቅድስት ኃይሌ ወርቁ",
		motherPhone: "+251911111107",
		motherIsAlive: true,
		emergencyFullName: "Bethlehem Mekonnen Haile",
		emergencyFullNameAm: "ቤተልሔም መኮንን ኃይሌ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222207",
	},
	{
		firstName: "Sara",
		firstNameAm: "ሳራ",
		middleName: "Tadesse",
		middleNameAm: "ታደሰ",
		lastName: "Bogale",
		lastNameAm: "ቦጋለ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1991-12-03"),
		birthPlace: "Adama",
		birthPlaceAm: "አዳማ",
		height: 158,
		weight: 54,
		bloodType: BloodType.AB_NEGATIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Oromo",
		faydaId: "ETH-8901234567",
		primaryPhone: "+251911234508",
		email: "sara.tadesse@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2017-08-15"),
		centerCode: "DRD",
		departmentCode: "MED",
		positionCode: "NURSE",
		rankCode: "SGT",
		currentSalaryStep: 2,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.SHIFT_24,
		addressSubCityCode: "AR",
		addressWoredaCode: "AR01",
		houseNumber: "456",
		motherFullName: "Almaz Bogale Desta",
		motherFullNameAm: "አልማዝ ቦጋለ ደስታ",
		motherPhone: "+251911111108",
		motherIsAlive: true,
		emergencyFullName: "Tadesse Bogale Haile",
		emergencyFullNameAm: "ታደሰ ቦጋለ ኃይሌ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222208",
	},
	{
		firstName: "Daniel",
		firstNameAm: "ዳንኤል",
		middleName: "Hailu",
		middleNameAm: "ኃይሉ",
		lastName: "Zeleke",
		lastNameAm: "ዘለቀ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1986-08-14"),
		birthPlace: "Dessie",
		birthPlaceAm: "ደሴ",
		height: 176,
		weight: 82,
		bloodType: BloodType.O_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Amhara",
		faydaId: "ETH-9012345678",
		drivingLicense: "AM-1234567",
		primaryPhone: "+251911234509",
		email: "daniel.hailu@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2009-10-01"),
		centerCode: "SRB",
		departmentCode: "SEC",
		positionCode: "DIR",
		rankCode: "LTCOL",
		currentSalaryStep: 5,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2013-04-18"),
		workScheduleType: WorkScheduleType.SHIFT_24,
		isTransfer: true,
		sourceOrganization: "Ethiopian Revenue and Customs Authority",
		originalEmploymentDate: new Date("2004-07-01"),
		addressSubCityCode: "AD",
		addressWoredaCode: "AD01",
		houseNumber: "678",
		motherFullName: "Tsehay Mekonnen Alemu",
		motherFullNameAm: "ፀሀይ መኮንን አለሙ",
		motherPhone: "+251911111109",
		motherIsAlive: true,
		emergencyFullName: "Marta Hailu Mekonnen",
		emergencyFullNameAm: "ማርታ ኃይሉ መኮንን",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222209",
	},
	{
		firstName: "Bethlehem",
		firstNameAm: "ቤተልሔም",
		middleName: "Lemma",
		middleNameAm: "ለማ",
		lastName: "Kassa",
		lastNameAm: "ካሳ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1993-05-20"),
		birthPlace: "Axum",
		birthPlaceAm: "አክሱም",
		height: 164,
		weight: 60,
		bloodType: BloodType.A_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Tigray",
		faydaId: "ETH-0123456789",
		primaryPhone: "+251911234510",
		email: "bethlehem.lemma@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2018-03-12"),
		centerCode: "SRB",
		departmentCode: "HR",
		positionCode: "HRSP",
		rankCode: "2LT",
		currentSalaryStep: 1,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "NK",
		addressWoredaCode: "NK01",
		houseNumber: "123",
		motherFullName: "Seble Tadesse Gebre",
		motherFullNameAm: "ሰብለ ታደሰ ገብረ",
		motherPhone: "+251911111110",
		motherIsAlive: true,
		emergencyFullName: "Lemma Kassa Tadesse",
		emergencyFullNameAm: "ለማ ካሳ ታደሰ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222210",
	},
	{
		firstName: "Getachew",
		firstNameAm: "ጌታቸው",
		middleName: "Negash",
		middleNameAm: "ነጋሽ",
		lastName: "Ayele",
		lastNameAm: "አየለ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1984-02-28"),
		birthPlace: "Shashemene",
		birthPlaceAm: "ሻሸመኔ",
		height: 179,
		weight: 84,
		bloodType: BloodType.B_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Oromo",
		faydaId: "ETH-1111111111",
		drivingLicense: "OR-2345678",
		primaryPhone: "+251911234511",
		email: "getachew.negash@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2007-07-07"),
		centerCode: "HQ",
		departmentCode: "SEC",
		positionCode: "SOFF",
		rankCode: "MAJ",
		currentSalaryStep: 6,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2011-08-22"),
		workScheduleType: WorkScheduleType.SHIFT_24,
		isTransfer: true,
		sourceOrganization: "Ethiopian Immigration Authority",
		originalEmploymentDate: new Date("2002-11-15"),
		addressSubCityCode: "KO",
		addressWoredaCode: "KO01",
		houseNumber: "345",
		motherFullName: "Aster Bekele Worku",
		motherFullNameAm: "አስቴር በቀለ ወርቁ",
		motherPhone: "+251911111111",
		motherIsAlive: true,
		emergencyFullName: "Meseret Negash Bekele",
		emergencyFullNameAm: "መሰረት ነጋሽ በቀለ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222211",
	},
	{
		firstName: "Kidist",
		firstNameAm: "ቅድስት",
		middleName: "Berhane",
		middleNameAm: "ብርሃኔ",
		lastName: "Gebrehiwot",
		lastNameAm: "ገብረሕይወት",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1989-10-10"),
		birthPlace: "Lalibela",
		birthPlaceAm: "ላሊበላ",
		height: 166,
		weight: 63,
		bloodType: BloodType.O_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Amhara",
		faydaId: "ETH-2222222222",
		primaryPhone: "+251911234512",
		email: "kidist.berhane@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2014-05-25"),
		centerCode: "KLT",
		departmentCode: "FIN",
		positionCode: "ACCT",
		rankCode: "CPT",
		currentSalaryStep: 4,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2018-02-14"),
		workScheduleType: WorkScheduleType.REGULAR,
		isTransfer: true,
		sourceOrganization: "Ministry of Finance",
		originalEmploymentDate: new Date("2010-02-01"),
		addressSubCityCode: "AK",
		addressWoredaCode: "AK03",
		houseNumber: "567",
		motherFullName: "Tigist Haile Desta",
		motherFullNameAm: "ትግስት ኃይሌ ደስታ",
		motherPhone: "+251911111112",
		motherIsAlive: true,
		emergencyFullName: "Berhane Gebrehiwot Haile",
		emergencyFullNameAm: "ብርሃኔ ገብረሕይወት ኃይሌ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222212",
	},
	{
		firstName: "Yohannes",
		firstNameAm: "ዮሐንስ",
		middleName: "Abate",
		middleNameAm: "አባተ",
		lastName: "Mengistu",
		lastNameAm: "መንግስቱ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1978-04-05"),
		birthPlace: "Harar",
		birthPlaceAm: "ሀረር",
		height: 174,
		weight: 76,
		bloodType: BloodType.A_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Harari",
		faydaId: "ETH-3333333333",
		drivingLicense: "HR-1234567",
		primaryPhone: "+251911234513",
		email: "yohannes.abate@fpc.gov.et",
		employeeType: EmployeeType.CIVILIAN,
		employmentDate: new Date("2010-09-18"),
		centerCode: "HQ",
		departmentCode: "ICT",
		positionCode: "DHEAD",
		currentSalary: 18500,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2005-11-25"),
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "BO",
		addressWoredaCode: "BO02",
		houseNumber: "789",
		uniqueAreaName: "Bole Atlas",
		motherFullName: "Worke Tadesse Gebre",
		motherFullNameAm: "ወርቄ ታደሰ ገብረ",
		motherPhone: "+251911111113",
		motherIsAlive: false,
		emergencyFullName: "Hiwot Abate Tadesse",
		emergencyFullNameAm: "ህይወት አባተ ታደሰ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222213",
	},
	{
		firstName: "Meseret",
		firstNameAm: "መሰረት",
		middleName: "Tessema",
		middleNameAm: "ተሰማ",
		lastName: "Woldemichael",
		lastNameAm: "ወልደሚካኤል",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1995-08-17"),
		birthPlace: "Debre Markos",
		birthPlaceAm: "ደብረ ማርቆስ",
		height: 161,
		weight: 56,
		bloodType: BloodType.B_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Amhara",
		faydaId: "ETH-4444444444",
		primaryPhone: "+251911234514",
		email: "meseret.tessema@fpc.gov.et",
		employeeType: EmployeeType.CIVILIAN,
		employmentDate: new Date("2019-01-10"),
		centerCode: "HQ",
		departmentCode: "ICT",
		positionCode: "ITSP",
		currentSalary: 12500,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "YK",
		addressWoredaCode: "YK02",
		houseNumber: "234",
		motherFullName: "Abebech Wolde Mekonnen",
		motherFullNameAm: "አበበች ወልደ መኮንን",
		motherPhone: "+251911111114",
		motherIsAlive: true,
		emergencyFullName: "Tessema Woldemichael Wolde",
		emergencyFullNameAm: "ተሰማ ወልደሚካኤል ወልደ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222214",
	},
	{
		firstName: "Almaz",
		firstNameAm: "አልማዝ",
		middleName: "Worku",
		middleNameAm: "ወርቁ",
		lastName: "Gebre",
		lastNameAm: "ገብረ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1982-11-22"),
		birthPlace: "Arba Minch",
		birthPlaceAm: "አርባ ምንጭ",
		height: 163,
		weight: 61,
		bloodType: BloodType.AB_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Gamo",
		faydaId: "ETH-5555555555",
		primaryPhone: "+251911234515",
		email: "almaz.worku@fpc.gov.et",
		employeeType: EmployeeType.CIVILIAN,
		employmentDate: new Date("2013-06-01"),
		centerCode: "KLT",
		departmentCode: "MED",
		positionCode: "DOCTOR",
		currentSalary: 22000,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2009-07-15"),
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "NK",
		addressWoredaCode: "NK02",
		houseNumber: "456",
		motherFullName: "Zenebech Haile Tadesse",
		motherFullNameAm: "ዘነበች ኃይሌ ታደሰ",
		motherPhone: "+251911111115",
		motherIsAlive: true,
		emergencyFullName: "Kebede Gebre Haile",
		emergencyFullNameAm: "ከበደ ገብረ ኃይሌ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222215",
	},
	{
		firstName: "Haile",
		firstNameAm: "ኃይሌ",
		middleName: "Assefa",
		middleNameAm: "አሰፋ",
		lastName: "Desta",
		lastNameAm: "ደስታ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1997-03-08"),
		birthPlace: "Nekemte",
		birthPlaceAm: "ነቀምት",
		height: 172,
		weight: 70,
		bloodType: BloodType.O_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Oromo",
		faydaId: "ETH-6666666666",
		primaryPhone: "+251911234516",
		email: "haile.assefa@fpc.gov.et",
		employeeType: EmployeeType.TEMPORARY,
		employmentDate: new Date("2024-06-01"),
		centerCode: "HQ",
		departmentCode: "LOG",
		positionCode: "AAST",
		contractStartDate: new Date("2024-06-01"),
		contractEndDate: new Date("2025-05-31"),
		contractAmount: 8500,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "LM",
		addressWoredaCode: "LM01",
		houseNumber: "678",
		motherFullName: "Hirut Mekonnen Alemu",
		motherFullNameAm: "ህሩት መኮንን አለሙ",
		motherPhone: "+251911111116",
		motherIsAlive: true,
		emergencyFullName: "Assefa Desta Mekonnen",
		emergencyFullNameAm: "አሰፋ ደስታ መኮንን",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222216",
	},
	{
		firstName: "Selamawit",
		firstNameAm: "ሰላማዊት",
		middleName: "Gebre",
		middleNameAm: "ገብረ",
		lastName: "Hailu",
		lastNameAm: "ኃይሉ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1998-09-14"),
		birthPlace: "Wolkite",
		birthPlaceAm: "ወልቂጤ",
		height: 159,
		weight: 52,
		bloodType: BloodType.A_POSITIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Gurage",
		faydaId: "ETH-7777777777",
		primaryPhone: "+251911234517",
		email: "selamawit.gebre@fpc.gov.et",
		employeeType: EmployeeType.TEMPORARY,
		employmentDate: new Date("2024-09-15"),
		centerCode: "KLT",
		departmentCode: "ADM",
		positionCode: "AAST",
		contractStartDate: new Date("2024-09-15"),
		contractEndDate: new Date("2025-09-14"),
		contractAmount: 8000,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "KO",
		addressWoredaCode: "KO02",
		houseNumber: "890",
		motherFullName: "Yeshi Tadesse Worku",
		motherFullNameAm: "የሺ ታደሰ ወርቁ",
		motherPhone: "+251911111117",
		motherIsAlive: true,
		emergencyFullName: "Gebre Hailu Tadesse",
		emergencyFullNameAm: "ገብረ ኃይሉ ታደሰ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222217",
	},
	{
		firstName: "Kebede",
		firstNameAm: "ከበደ",
		middleName: "Mekonnen",
		middleNameAm: "መኮንን",
		lastName: "Tadesse",
		lastNameAm: "ታደሰ",
		gender: Gender.MALE,
		dateOfBirth: new Date("1981-07-19"),
		birthPlace: "Debre Berhan",
		birthPlaceAm: "ደብረ ብርሃን",
		height: 177,
		weight: 79,
		bloodType: BloodType.B_NEGATIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Amhara",
		faydaId: "ETH-8888888888",
		drivingLicense: "AM-3456789",
		primaryPhone: "+251911234518",
		email: "kebede.mekonnen@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2006-03-20"),
		centerCode: "HQ",
		departmentCode: "LEG",
		positionCode: "LEGAL",
		rankCode: "MAJ",
		currentSalaryStep: 6,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2010-05-30"),
		workScheduleType: WorkScheduleType.REGULAR,
		isTransfer: true,
		sourceOrganization: "Federal Attorney General",
		originalEmploymentDate: new Date("2001-09-05"),
		addressSubCityCode: "GU",
		addressWoredaCode: "GU02",
		houseNumber: "123",
		motherFullName: "Etalem Bekele Haile",
		motherFullNameAm: "እጣለም በቀለ ኃይሌ",
		motherPhone: "+251911111118",
		motherIsAlive: true,
		emergencyFullName: "Tigist Mekonnen Bekele",
		emergencyFullNameAm: "ትግስት መኮንን በቀለ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222218",
	},
	{
		firstName: "Rahel",
		firstNameAm: "ራሄል",
		middleName: "Wolde",
		middleNameAm: "ወልደ",
		lastName: "Negash",
		lastNameAm: "ነጋሽ",
		gender: Gender.FEMALE,
		dateOfBirth: new Date("1994-06-11"),
		birthPlace: "Sodo",
		birthPlaceAm: "ሶዶ",
		height: 160,
		weight: 55,
		bloodType: BloodType.O_NEGATIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		ethnicity: "Wolayta",
		faydaId: "ETH-9999999999",
		primaryPhone: "+251911234519",
		email: "rahel.wolde@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2019-11-01"),
		centerCode: "ZWY",
		departmentCode: "FIN",
		positionCode: "ACCT",
		rankCode: "1LT",
		currentSalaryStep: 2,
		maritalStatus: MaritalStatus.SINGLE,
		workScheduleType: WorkScheduleType.REGULAR,
		addressSubCityCode: "BO",
		addressWoredaCode: "BO03",
		houseNumber: "456",
		motherFullName: "Mulu Haile Gebre",
		motherFullNameAm: "ሙሉ ኃይሌ ገብረ",
		motherPhone: "+251911111119",
		motherIsAlive: true,
		emergencyFullName: "Wolde Negash Haile",
		emergencyFullNameAm: "ወልደ ነጋሽ ኃይሌ",
		emergencyRelationship: "FATHER",
		emergencyPhone: "+251911222219",
	},
	{
		firstName: "Bekele",
		firstNameAm: "በቀለ",
		middleName: "Tadesse",
		middleNameAm: "ታደሰ",
		lastName: "Asfaw",
		lastNameAm: "አስፋው",
		gender: Gender.MALE,
		dateOfBirth: new Date("1979-12-25"),
		birthPlace: "Kombolcha",
		birthPlaceAm: "ኮምቦልቻ",
		height: 181,
		weight: 86,
		bloodType: BloodType.AB_NEGATIVE,
		eyeColor: "Brown",
		hairColor: "Black",
		distinguishingMarks: "Birthmark on left arm",
		ethnicity: "Amhara",
		faydaId: "ETH-0000000000",
		drivingLicense: "AM-4567890",
		primaryPhone: "+251911234520",
		email: "bekele.tadesse@fpc.gov.et",
		employeeType: EmployeeType.MILITARY,
		employmentDate: new Date("2004-08-10"),
		centerCode: "DRD",
		departmentCode: "TRN",
		positionCode: "DHEAD",
		rankCode: "COL",
		currentSalaryStep: 8,
		maritalStatus: MaritalStatus.MARRIED,
		marriageDate: new Date("2007-03-18"),
		workScheduleType: WorkScheduleType.REGULAR,
		isTransfer: true,
		sourceOrganization: "Ethiopian Military Academy",
		originalEmploymentDate: new Date("1998-12-01"),
		addressSubCityCode: "YK",
		addressWoredaCode: "YK03",
		houseNumber: "789",
		uniqueAreaName: "CMC Area",
		motherFullName: "Dinke Worku Tadesse",
		motherFullNameAm: "ድንቄ ወርቁ ታደሰ",
		motherPhone: "+251911111120",
		motherIsAlive: false,
		motherAddress: "Dessie, Wollo",
		emergencyFullName: "Aster Tadesse Worku",
		emergencyFullNameAm: "አስቴር ታደሰ ወርቁ",
		emergencyRelationship: "SPOUSE",
		emergencyPhone: "+251911222220",
		emergencyAltPhone: "+251933333320",
	},
];

const generateEmployeeId = (type: EmployeeType, number: number, year: number): string => {
	const prefix = EMPLOYEE_ID_PREFIXES[type];
	const paddedNumber = String(number).padStart(4, "0");
	const yearSuffix = String(year).slice(-2);
	return `${prefix}-${paddedNumber}/${yearSuffix}`;
};

export const seedEmployees = async (prisma: PrismaClient, tenantId: string): Promise<void> => {
	const existingCount = await prisma.employee.count({ where: { tenantId } });

	if (existingCount >= 15) {
		console.log(`Already have ${existingCount} employees, skipping employee seed...`);
		return;
	}

	const currentYear = new Date().getFullYear();
	const counters: Record<string, number> = {
		[`employeeIdCounter_MILITARY_${currentYear}`]: 0,
		[`employeeIdCounter_CIVILIAN_${currentYear}`]: 0,
		[`employeeIdCounter_TEMPORARY_${currentYear}`]: 0,
	};

	const addisAbabaRegion = await prisma.region.findFirst({
		where: { tenantId, code: "AA" },
	});

	if (!addisAbabaRegion) {
		console.log("Addis Ababa region not found, cannot seed employees");
		return;
	}

	for (const emp of EMPLOYEES_DATA) {
		const center = await prisma.center.findFirst({
			where: { tenantId, code: emp.centerCode },
		});

		if (!center) {
			console.log(`Center ${emp.centerCode} not found, skipping employee ${emp.firstName}...`);
			continue;
		}

		const department = await prisma.department.findFirst({
			where: { tenantId, code: emp.departmentCode },
		});

		if (!department) {
			console.log(`Department ${emp.departmentCode} not found, skipping employee ${emp.firstName}...`);
			continue;
		}

		const position = await prisma.position.findFirst({
			where: { tenantId, code: emp.positionCode },
		});

		if (!position) {
			console.log(`Position ${emp.positionCode} not found, skipping employee ${emp.firstName}...`);
			continue;
		}

		let rank = null;
		if (emp.rankCode) {
			rank = await prisma.militaryRank.findFirst({
				where: { code: emp.rankCode, tenantId: null },
			});

			if (!rank) {
				console.log(`Rank ${emp.rankCode} not found, skipping employee ${emp.firstName}...`);
				continue;
			}
		}

		const subCity = await prisma.subCity.findFirst({
			where: { tenantId, code: emp.addressSubCityCode },
		});

		if (!subCity) {
			console.log(`SubCity ${emp.addressSubCityCode} not found, skipping employee ${emp.firstName}...`);
			continue;
		}

		const woreda = await prisma.woreda.findFirst({
			where: { tenantId, code: emp.addressWoredaCode },
		});

		if (!woreda) {
			console.log(`Woreda ${emp.addressWoredaCode} not found, skipping employee ${emp.firstName}...`);
			continue;
		}

		const counterKey = `employeeIdCounter_${emp.employeeType}_${currentYear}`;
		counters[counterKey]++;
		const employeeId = generateEmployeeId(emp.employeeType, counters[counterKey], currentYear);

		const fullName = `${emp.firstName} ${emp.middleName} ${emp.lastName}`;
		const fullNameAm = `${emp.firstNameAm} ${emp.middleNameAm} ${emp.lastNameAm}`;

		const employee = await prisma.employee.create({
			data: {
				tenantId,
				centerId: center.id,
				employeeId,
				employeeType: emp.employeeType,
				firstName: emp.firstName,
				firstNameAm: emp.firstNameAm,
				middleName: emp.middleName,
				middleNameAm: emp.middleNameAm,
				lastName: emp.lastName,
				lastNameAm: emp.lastNameAm,
				fullName,
				fullNameAm,
				gender: emp.gender,
				dateOfBirth: emp.dateOfBirth,
				birthPlace: emp.birthPlace,
				birthPlaceAm: emp.birthPlaceAm,
				height: emp.height,
				weight: emp.weight,
				bloodType: emp.bloodType,
				eyeColor: emp.eyeColor,
				hairColor: emp.hairColor,
				distinguishingMarks: emp.distinguishingMarks,
				nationality: "Ethiopian",
				ethnicity: emp.ethnicity,
				faydaId: emp.faydaId,
				passportNumber: emp.passportNumber,
				drivingLicense: emp.drivingLicense,
				primaryPhone: emp.primaryPhone,
				secondaryPhone: emp.secondaryPhone,
				email: emp.email,
				departmentId: department.id,
				positionId: position.id,
				rankId: rank?.id,
				employmentDate: emp.employmentDate,
				workScheduleType: emp.workScheduleType,
				maritalStatus: emp.maritalStatus,
				marriageDate: emp.marriageDate,
				currentSalaryStep: emp.currentSalaryStep ?? 0,
				currentSalary: emp.currentSalary,
				salaryEffectiveDate: emp.employmentDate,
				contractStartDate: emp.contractStartDate,
				contractEndDate: emp.contractEndDate,
				contractAmount: emp.contractAmount,
				isTransfer: emp.isTransfer ?? false,
				sourceOrganization: emp.sourceOrganization,
				originalEmploymentDate: emp.originalEmploymentDate,
				status: EmployeeStatus.ACTIVE,
			},
		});

		await prisma.employeeAddress.create({
			data: {
				tenantId,
				employeeId: employee.id,
				addressType: "CURRENT",
				regionId: addisAbabaRegion.id,
				subCityId: subCity.id,
				woredaId: woreda.id,
				houseNumber: emp.houseNumber,
				uniqueAreaName: emp.uniqueAreaName,
				isPrimary: true,
			},
		});

		await prisma.employeeMotherInfo.create({
			data: {
				tenantId,
				employeeId: employee.id,
				fullName: emp.motherFullName,
				fullNameAm: emp.motherFullNameAm,
				phone: emp.motherPhone,
				isAlive: emp.motherIsAlive,
				address: emp.motherAddress,
			},
		});

		await prisma.employeeEmergencyContact.create({
			data: {
				tenantId,
				employeeId: employee.id,
				fullName: emp.emergencyFullName,
				fullNameAm: emp.emergencyFullNameAm,
				relationship: emp.emergencyRelationship,
				phone: emp.emergencyPhone,
				alternativePhone: emp.emergencyAltPhone,
				priority: 1,
			},
		});

		console.log(`Created employee: ${fullName} (${employeeId}) - ${emp.employeeType}`);
	}

	const tenant = await prisma.tenant.findUnique({
		where: { id: tenantId },
		select: { settings: true },
	});

	const existingSettings = (tenant?.settings as Prisma.JsonObject) ?? {};
	const updatedSettings: Prisma.JsonObject = {
		...existingSettings,
		...counters,
	};
	await prisma.tenant.update({
		where: { id: tenantId },
		data: {
			settings: updatedSettings,
		},
	});

	console.log("Updated tenant employee ID counters");
};
