import { PrismaClient } from "@prisma/client";

const LEAVE_TYPES = [
	{
		code: "ANNUAL",
		name: "Annual Leave",
		nameAm: "አመታዊ ፈቃድ",
		description: "Standard annual leave entitlement",
		defaultDays: 20,
		isPaid: true,
		accrualMethod: "YEARLY",
		allowCarryOver: true,
		maxCarryOverDays: 10,
		carryOverExpiryYears: 1,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN", "TEMPORARY"],
		requiresDocument: false,
		minNoticeDays: 7,
		holidayExtendsLeave: true,
		shiftWorkerException: true,
		sortOrder: 1,
	},
	{
		code: "SICK",
		name: "Sick Leave",
		nameAm: "የሕመም ፈቃድ",
		description: "Leave for illness or medical treatment",
		defaultDays: 30,
		isPaid: true,
		accrualMethod: "YEARLY",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN", "TEMPORARY"],
		requiresDocument: true,
		minNoticeDays: 0,
		holidayExtendsLeave: false,
		shiftWorkerException: true,
		sortOrder: 2,
	},
	{
		code: "MATERNITY",
		name: "Maternity Leave",
		nameAm: "የወሊድ ፈቃድ",
		description: "Leave for childbirth and postnatal care",
		defaultDays: 120,
		isPaid: true,
		accrualMethod: "EVENT",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN"],
		applicableGender: "FEMALE",
		requiresDocument: true,
		minNoticeDays: 30,
		holidayExtendsLeave: false,
		shiftWorkerException: false,
		sortOrder: 3,
	},
	{
		code: "PATERNITY",
		name: "Paternity Leave",
		nameAm: "የአባትነት ፈቃድ",
		description: "Leave for fathers after childbirth",
		defaultDays: 15,
		isPaid: true,
		accrualMethod: "EVENT",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN"],
		applicableGender: "MALE",
		requiresDocument: true,
		minNoticeDays: 7,
		holidayExtendsLeave: true,
		shiftWorkerException: true,
		sortOrder: 4,
	},
	{
		code: "BEREAVEMENT",
		name: "Bereavement Leave",
		nameAm: "የሀዘን ፈቃድ",
		description: "Leave for death of immediate family member",
		defaultDays: 7,
		isPaid: true,
		accrualMethod: "EVENT",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN", "TEMPORARY"],
		requiresDocument: true,
		minNoticeDays: 0,
		holidayExtendsLeave: false,
		shiftWorkerException: true,
		sortOrder: 5,
	},
	{
		code: "MARRIAGE",
		name: "Marriage Leave",
		nameAm: "የጋብቻ ፈቃድ",
		description: "Leave for employee's own wedding",
		defaultDays: 5,
		isPaid: true,
		accrualMethod: "EVENT",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN"],
		requiresDocument: true,
		minNoticeDays: 14,
		holidayExtendsLeave: true,
		shiftWorkerException: true,
		sortOrder: 6,
	},
	{
		code: "STUDY",
		name: "Study Leave",
		nameAm: "የትምህርት ፈቃድ",
		description: "Leave for educational purposes",
		defaultDays: 30,
		isPaid: false,
		accrualMethod: "YEARLY",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN"],
		requiresDocument: true,
		minNoticeDays: 30,
		holidayExtendsLeave: false,
		shiftWorkerException: false,
		sortOrder: 7,
	},
	{
		code: "UNPAID",
		name: "Unpaid Leave",
		nameAm: "ያለ ደመወዝ ፈቃድ",
		description: "Leave without pay",
		defaultDays: 30,
		isPaid: false,
		accrualMethod: "REQUEST",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN", "TEMPORARY"],
		requiresDocument: false,
		minNoticeDays: 14,
		holidayExtendsLeave: false,
		shiftWorkerException: false,
		sortOrder: 8,
	},
	{
		code: "SPECIAL",
		name: "Special Leave",
		nameAm: "ልዩ ፈቃድ",
		description: "Special circumstances leave approved by management",
		defaultDays: 10,
		isPaid: true,
		accrualMethod: "REQUEST",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN"],
		requiresDocument: true,
		minNoticeDays: 3,
		holidayExtendsLeave: true,
		shiftWorkerException: true,
		sortOrder: 9,
	},
	{
		code: "TRAINING",
		name: "Training Leave",
		nameAm: "የስልጠና ፈቃድ",
		description: "Leave for official training programs",
		defaultDays: 20,
		isPaid: true,
		accrualMethod: "REQUEST",
		allowCarryOver: false,
		applicableEmployeeTypes: ["MILITARY", "CIVILIAN"],
		requiresDocument: true,
		minNoticeDays: 7,
		holidayExtendsLeave: false,
		shiftWorkerException: false,
		sortOrder: 10,
	},
];

export const seedLeaveTypes = async (prisma: PrismaClient, tenantId: string): Promise<void> => {
	for (const leaveType of LEAVE_TYPES) {
		const existing = await prisma.leaveType.findFirst({
			where: { tenantId, code: leaveType.code },
		});

		if (existing) {
			console.log(`Leave type ${leaveType.code} already exists, skipping...`);
			continue;
		}

		await prisma.leaveType.create({
			data: {
				tenantId,
				code: leaveType.code,
				name: leaveType.name,
				nameAm: leaveType.nameAm,
				description: leaveType.description,
				defaultDays: leaveType.defaultDays,
				isPaid: leaveType.isPaid,
				accrualMethod: leaveType.accrualMethod,
				allowCarryOver: leaveType.allowCarryOver,
				maxCarryOverDays: leaveType.maxCarryOverDays,
				carryOverExpiryYears: leaveType.carryOverExpiryYears,
				applicableEmployeeTypes: leaveType.applicableEmployeeTypes,
				applicableGender: leaveType.applicableGender,
				requiresDocument: leaveType.requiresDocument,
				minNoticeDays: leaveType.minNoticeDays,
				holidayExtendsLeave: leaveType.holidayExtendsLeave,
				shiftWorkerException: leaveType.shiftWorkerException,
				sortOrder: leaveType.sortOrder,
				isActive: true,
			},
		});

		console.log(`Created leave type: ${leaveType.name} (${leaveType.code})`);
	}
};
