export const BLOOD_TYPE_OPTIONS = [
	{ value: "A_POSITIVE", label: "A+" },
	{ value: "A_NEGATIVE", label: "A-" },
	{ value: "B_POSITIVE", label: "B+" },
	{ value: "B_NEGATIVE", label: "B-" },
	{ value: "AB_POSITIVE", label: "AB+" },
	{ value: "AB_NEGATIVE", label: "AB-" },
	{ value: "O_POSITIVE", label: "O+" },
	{ value: "O_NEGATIVE", label: "O-" },
] as const;

export const WORK_SCHEDULE_OPTIONS = [
	{ value: "REGULAR", label: "Regular" },
	{ value: "SHIFT_24", label: "24-Hour Shift" },
] as const;

export const SALARY_STEP_OPTIONS = Array.from({ length: 10 }, (_, i) => ({
	value: String(i),
	label: `Step ${i}`,
}));

export const MARITAL_STATUS_OPTIONS = [
	{ value: "SINGLE", label: "Single" },
	{ value: "MARRIED", label: "Married" },
	{ value: "DIVORCED", label: "Divorced" },
	{ value: "WIDOWED", label: "Widowed" },
] as const;

export const GENDER_OPTIONS = [
	{ value: "MALE", label: "Male" },
	{ value: "FEMALE", label: "Female" },
] as const;

export const RELATIONSHIP_OPTIONS = [
	{ value: "SPOUSE", label: "Spouse" },
	{ value: "PARENT", label: "Parent" },
	{ value: "SIBLING", label: "Sibling" },
	{ value: "CHILD", label: "Child" },
	{ value: "FRIEND", label: "Friend" },
	{ value: "OTHER", label: "Other" },
] as const;

export const REGION_OPTIONS = [
	{ value: "addis-ababa", label: "Addis Ababa" },
	{ value: "afar", label: "Afar" },
	{ value: "amhara", label: "Amhara" },
	{ value: "benishangul-gumuz", label: "Benishangul-Gumuz" },
	{ value: "dire-dawa", label: "Dire Dawa" },
	{ value: "gambela", label: "Gambela" },
	{ value: "harari", label: "Harari" },
	{ value: "oromia", label: "Oromia" },
	{ value: "sidama", label: "Sidama" },
	{ value: "somali", label: "Somali" },
	{ value: "south-ethiopia", label: "South Ethiopia" },
	{ value: "south-west-ethiopia", label: "South West Ethiopia" },
	{ value: "tigray", label: "Tigray" },
] as const;

export const SUB_CITY_OPTIONS: Record<string, Array<{ value: string; label: string }>> = {
	"addis-ababa": [
		{ value: "addis-ketema", label: "Addis Ketema" },
		{ value: "akaky-kaliti", label: "Akaky Kaliti" },
		{ value: "arada", label: "Arada" },
		{ value: "bole", label: "Bole" },
		{ value: "gulele", label: "Gulele" },
		{ value: "kirkos", label: "Kirkos" },
		{ value: "kolfe-keranio", label: "Kolfe Keranio" },
		{ value: "lideta", label: "Lideta" },
		{ value: "nifas-silk-lafto", label: "Nifas Silk-Lafto" },
		{ value: "yeka", label: "Yeka" },
		{ value: "lemi-kura", label: "Lemi Kura" },
	],
	amhara: [
		{ value: "bahir-dar", label: "Bahir Dar City" },
		{ value: "gondar", label: "Gondar City" },
		{ value: "dessie", label: "Dessie City" },
		{ value: "debre-birhan", label: "Debre Birhan City" },
		{ value: "north-gondar", label: "North Gondar Zone" },
		{ value: "south-gondar", label: "South Gondar Zone" },
		{ value: "central-gondar", label: "Central Gondar Zone" },
		{ value: "west-gondar", label: "West Gondar Zone" },
		{ value: "north-wollo", label: "North Wollo Zone" },
		{ value: "south-wollo", label: "South Wollo Zone" },
		{ value: "north-shewa", label: "North Shewa Zone" },
		{ value: "east-gojjam", label: "East Gojjam Zone" },
		{ value: "west-gojjam", label: "West Gojjam Zone" },
		{ value: "awi", label: "Awi Zone" },
		{ value: "wag-hemra", label: "Wag Hemra Zone" },
		{ value: "oromia-special", label: "Oromia Special Zone" },
	],
	oromia: [
		{ value: "addis-ababa-surrounding", label: "Addis Ababa Surrounding (Finfine)" },
		{ value: "arsi", label: "Arsi Zone" },
		{ value: "bale", label: "Bale Zone" },
		{ value: "borena", label: "Borena Zone" },
		{ value: "east-hararghe", label: "East Hararghe Zone" },
		{ value: "west-hararghe", label: "West Hararghe Zone" },
		{ value: "east-shewa", label: "East Shewa Zone" },
		{ value: "west-shewa", label: "West Shewa Zone" },
		{ value: "north-shewa-oromia", label: "North Shewa Zone" },
		{ value: "south-west-shewa", label: "South West Shewa Zone" },
		{ value: "east-wellega", label: "East Wellega Zone" },
		{ value: "west-wellega", label: "West Wellega Zone" },
		{ value: "horo-guduru", label: "Horo Guduru Wellega Zone" },
		{ value: "jimma", label: "Jimma Zone" },
		{ value: "illu-aba-bora", label: "Illu Aba Bora Zone" },
		{ value: "guji", label: "Guji Zone" },
		{ value: "west-guji", label: "West Guji Zone" },
	],
	tigray: [
		{ value: "mekelle", label: "Mekelle City" },
		{ value: "central-tigray", label: "Central Zone" },
		{ value: "eastern-tigray", label: "Eastern Zone" },
		{ value: "north-western-tigray", label: "North Western Zone" },
		{ value: "southern-tigray", label: "Southern Zone" },
		{ value: "western-tigray", label: "Western Zone" },
	],
	"south-ethiopia": [
		{ value: "hawassa", label: "Hawassa City" },
		{ value: "gedeo", label: "Gedeo Zone" },
		{ value: "kembata-tembaro", label: "Kembata Tembaro Zone" },
		{ value: "hadiya", label: "Hadiya Zone" },
		{ value: "halaba", label: "Halaba Special Woreda" },
		{ value: "silte", label: "Silte Zone" },
		{ value: "gurage", label: "Gurage Zone" },
		{ value: "wolaita", label: "Wolaita Zone" },
		{ value: "dawro", label: "Dawro Zone" },
		{ value: "gamo", label: "Gamo Zone" },
		{ value: "gofa", label: "Gofa Zone" },
		{ value: "south-omo", label: "South Omo Zone" },
	],
	"south-west-ethiopia": [
		{ value: "bench-sheko", label: "Bench Sheko Zone" },
		{ value: "kaffa", label: "Kaffa Zone" },
		{ value: "sheka", label: "Sheka Zone" },
		{ value: "west-omo", label: "West Omo Zone" },
		{ value: "dawro-sw", label: "Dawro Zone" },
		{ value: "konta", label: "Konta Special Woreda" },
	],
	sidama: [
		{ value: "hawassa-sidama", label: "Hawassa City" },
		{ value: "dale", label: "Dale Woreda" },
		{ value: "shebedino", label: "Shebedino Woreda" },
		{ value: "wondo-genet", label: "Wondo Genet Woreda" },
		{ value: "boricha", label: "Boricha Woreda" },
		{ value: "aleta-wondo", label: "Aleta Wondo Woreda" },
	],
	somali: [
		{ value: "jigjiga", label: "Jigjiga City" },
		{ value: "fafan", label: "Fafan Zone" },
		{ value: "jarar", label: "Jarar Zone" },
		{ value: "nogob", label: "Nogob Zone" },
		{ value: "dollo", label: "Dollo Zone" },
		{ value: "korahe", label: "Korahe Zone" },
		{ value: "shabelle", label: "Shabelle Zone" },
		{ value: "afder", label: "Afder Zone" },
		{ value: "liben", label: "Liben Zone" },
		{ value: "sitti", label: "Sitti Zone" },
		{ value: "erer", label: "Erer Zone" },
	],
	afar: [
		{ value: "semera", label: "Semera City" },
		{ value: "zone-1", label: "Zone 1 (Awsi Rasu)" },
		{ value: "zone-2", label: "Zone 2 (Kilbet Rasu)" },
		{ value: "zone-3", label: "Zone 3 (Gabi Rasu)" },
		{ value: "zone-4", label: "Zone 4 (Fantena Rasu)" },
		{ value: "zone-5", label: "Zone 5 (Hari Rasu)" },
	],
	"benishangul-gumuz": [
		{ value: "assosa", label: "Assosa City" },
		{ value: "assosa-zone", label: "Assosa Zone" },
		{ value: "kamashi", label: "Kamashi Zone" },
		{ value: "metekel", label: "Metekel Zone" },
	],
	gambela: [
		{ value: "gambela-city", label: "Gambela City" },
		{ value: "anuak", label: "Anuak Zone" },
		{ value: "nuer", label: "Nuer Zone" },
		{ value: "mezhenger", label: "Mezhenger Zone" },
	],
	"dire-dawa": [
		{ value: "dire-dawa-city", label: "Dire Dawa City" },
		{ value: "dire-dawa-rural", label: "Dire Dawa Rural" },
	],
	harari: [
		{ value: "harar-city", label: "Harar City" },
		{ value: "harar-rural", label: "Harar Rural" },
	],
} as const;

export const WOREDA_OPTIONS: Record<string, Array<{ value: string; label: string }>> = {
	"addis-ketema": [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
		{ value: "woreda-05", label: "Woreda 05" },
	],
	"akaky-kaliti": [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
	],
	arada: [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
	],
	bole: [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
		{ value: "woreda-05", label: "Woreda 05" },
	],
	gulele: [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
	],
	kirkos: [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
	],
	"kolfe-keranio": [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
		{ value: "woreda-05", label: "Woreda 05" },
	],
	lideta: [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
	],
	"nifas-silk-lafto": [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
	],
	yeka: [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
		{ value: "woreda-04", label: "Woreda 04" },
		{ value: "woreda-05", label: "Woreda 05" },
	],
	"lemi-kura": [
		{ value: "woreda-01", label: "Woreda 01" },
		{ value: "woreda-02", label: "Woreda 02" },
		{ value: "woreda-03", label: "Woreda 03" },
	],
	"bahir-dar": [
		{ value: "bahir-dar-zuria", label: "Bahir Dar Zuria" },
		{ value: "fasilo", label: "Fasilo" },
		{ value: "gish-abay", label: "Gish Abay" },
		{ value: "sefene-selam", label: "Sefene Selam" },
		{ value: "tana", label: "Tana" },
		{ value: "belay-zeleke", label: "Belay Zeleke" },
	],
	gondar: [
		{ value: "azezo", label: "Azezo" },
		{ value: "maraki", label: "Maraki" },
		{ value: "kebele-11", label: "Kebele 11" },
		{ value: "kebele-12", label: "Kebele 12" },
		{ value: "kebele-18", label: "Kebele 18" },
	],
	dessie: [
		{ value: "dessie-zuria", label: "Dessie Zuria" },
		{ value: "segno-gebeya", label: "Segno Gebeya" },
		{ value: "hotie", label: "Hotie" },
		{ value: "arada-dessie", label: "Arada" },
	],
	"debre-birhan": [
		{ value: "debre-birhan-zuria", label: "Debre Birhan Zuria" },
		{ value: "kebele-01", label: "Kebele 01" },
		{ value: "kebele-02", label: "Kebele 02" },
		{ value: "kebele-03", label: "Kebele 03" },
	],
	"north-gondar": [
		{ value: "debark", label: "Debark" },
		{ value: "dabat", label: "Dabat" },
		{ value: "wegera", label: "Wegera" },
		{ value: "addi-arkay", label: "Addi Arkay" },
		{ value: "beyeda", label: "Beyeda" },
		{ value: "janamora", label: "Janamora" },
	],
	"south-gondar": [
		{ value: "debre-tabor", label: "Debre Tabor" },
		{ value: "fogera", label: "Fogera" },
		{ value: "libo-kemkem", label: "Libo Kemkem" },
		{ value: "dera", label: "Dera" },
		{ value: "estie", label: "Estie" },
		{ value: "farta", label: "Farta" },
		{ value: "lay-gayint", label: "Lay Gayint" },
		{ value: "tach-gayint", label: "Tach Gayint" },
		{ value: "simada", label: "Simada" },
	],
	"central-gondar": [
		{ value: "gondar-zuria", label: "Gondar Zuria" },
		{ value: "wogera", label: "Wogera" },
		{ value: "dembiya", label: "Dembiya" },
		{ value: "chilga", label: "Chilga" },
		{ value: "takusa", label: "Takusa" },
		{ value: "lay-armachiho", label: "Lay Armachiho" },
	],
	"west-gondar": [
		{ value: "metema", label: "Metema" },
		{ value: "quara", label: "Quara" },
		{ value: "alefa", label: "Alefa" },
		{ value: "tach-armachiho", label: "Tach Armachiho" },
		{ value: "mirab-armachiho", label: "Mirab Armachiho" },
	],
	"north-wollo": [
		{ value: "woldia", label: "Woldia" },
		{ value: "kobo", label: "Kobo" },
		{ value: "habru", label: "Habru" },
		{ value: "gubalafto", label: "Gubalafto" },
		{ value: "meket", label: "Meket" },
		{ value: "gidan", label: "Gidan" },
		{ value: "wadla", label: "Wadla" },
		{ value: "lasta", label: "Lasta" },
		{ value: "bugna", label: "Bugna" },
	],
	"south-wollo": [
		{ value: "kombolcha", label: "Kombolcha" },
		{ value: "dessie-zuria-sw", label: "Dessie Zuria" },
		{ value: "kutaber", label: "Kutaber" },
		{ value: "tehuledere", label: "Tehuledere" },
		{ value: "kalu", label: "Kalu" },
		{ value: "ambassel", label: "Ambassel" },
		{ value: "wereilu", label: "Wereilu" },
		{ value: "legambo", label: "Legambo" },
		{ value: "tenta", label: "Tenta" },
		{ value: "sayint", label: "Sayint" },
		{ value: "mekdela", label: "Mekdela" },
	],
	"north-shewa": [
		{ value: "debre-berhan", label: "Debre Berhan" },
		{ value: "ankober", label: "Ankober" },
		{ value: "basona-werana", label: "Basona Werana" },
		{ value: "efratana-gidim", label: "Efratana Gidim" },
		{ value: "ensaro", label: "Ensaro" },
		{ value: "hagere-mariam-kesem", label: "Hagere Mariam Kesem" },
		{ value: "kewet", label: "Kewet" },
		{ value: "menz-gera-midir", label: "Menz Gera Midir" },
		{ value: "menz-keya-gebreal", label: "Menz Keya Gebreal" },
		{ value: "menz-mama-midir", label: "Menz Mama Midir" },
		{ value: "minjar-shenkora", label: "Minjar Shenkora" },
		{ value: "moretna-jiru", label: "Moretna Jiru" },
		{ value: "saya-debre-libanos", label: "Saya Debre Libanos" },
		{ value: "tarma-ber", label: "Tarma Ber" },
	],
	"east-gojjam": [
		{ value: "debre-markos", label: "Debre Markos" },
		{ value: "gozamin", label: "Gozamin" },
		{ value: "machakel", label: "Machakel" },
		{ value: "debay-telatgen", label: "Debay Telatgen" },
		{ value: "shebel-berenta", label: "Shebel Berenta" },
		{ value: "enemay", label: "Enemay" },
		{ value: "enarj-enawga", label: "Enarj Enawga" },
		{ value: "goncha-siso-enese", label: "Goncha Siso Enese" },
		{ value: "hulet-eju-enese", label: "Hulet Eju Enese" },
		{ value: "enebse-sar-midir", label: "Enebse Sar Midir" },
		{ value: "awabel", label: "Awabel" },
		{ value: "baso-liben", label: "Baso Liben" },
		{ value: "bibugn", label: "Bibugn" },
		{ value: "dejen", label: "Dejen" },
	],
	"west-gojjam": [
		{ value: "finote-selam", label: "Finote Selam" },
		{ value: "bahir-dar-zuria-wg", label: "Bahir Dar Zuria" },
		{ value: "mecha", label: "Mecha" },
		{ value: "yilmana-densa", label: "Yilmana Densa" },
		{ value: "quarit", label: "Quarit" },
		{ value: "sekela", label: "Sekela" },
		{ value: "dega-damot", label: "Dega Damot" },
		{ value: "jabi-tehnan", label: "Jabi Tehnan" },
		{ value: "bure", label: "Bure" },
		{ value: "womberima", label: "Womberima" },
		{ value: "dembecha", label: "Dembecha" },
		{ value: "south-achefer", label: "South Achefer" },
		{ value: "north-achefer", label: "North Achefer" },
	],
	awi: [
		{ value: "injibara", label: "Injibara" },
		{ value: "banja", label: "Banja" },
		{ value: "fagta-lekoma", label: "Fagta Lekoma" },
		{ value: "dangila", label: "Dangila" },
		{ value: "guangua", label: "Guangua" },
		{ value: "ankesha-guagusa", label: "Ankesha Guagusa" },
		{ value: "zigem", label: "Zigem" },
	],
	"wag-hemra": [
		{ value: "sekota", label: "Sekota" },
		{ value: "dahna", label: "Dahna" },
		{ value: "ziquala", label: "Ziquala" },
		{ value: "gazgibla", label: "Gazgibla" },
		{ value: "abergele", label: "Abergele" },
		{ value: "sehala", label: "Sehala" },
	],
	"oromia-special": [
		{ value: "kemise", label: "Kemise" },
		{ value: "artuma-fursi", label: "Artuma Fursi" },
		{ value: "bati", label: "Bati" },
		{ value: "dawa-chefa", label: "Dawa Chefa" },
	],
	mekelle: [
		{ value: "kedamay-weyane", label: "Kedamay Weyane" },
		{ value: "hawelti", label: "Hawelti" },
		{ value: "ayder", label: "Ayder" },
		{ value: "hadnet", label: "Hadnet" },
		{ value: "adi-haki", label: "Adi Haki" },
		{ value: "semien", label: "Semien" },
		{ value: "quiha", label: "Quiha" },
	],
	"central-tigray": [
		{ value: "axum", label: "Axum" },
		{ value: "adwa", label: "Adwa" },
		{ value: "laelay-maychew", label: "Laelay Maychew" },
		{ value: "tahtay-maychew", label: "Tahtay Maychew" },
		{ value: "werie-leke", label: "Werie Leke" },
		{ value: "ahferom", label: "Ahferom" },
		{ value: "mereb-leke", label: "Mereb Leke" },
	],
	"eastern-tigray": [
		{ value: "adigrat", label: "Adigrat" },
		{ value: "wukro", label: "Wukro" },
		{ value: "hawzen", label: "Hawzen" },
		{ value: "kilte-awlaelo", label: "Kilte Awlaelo" },
		{ value: "atsbi-wonberta", label: "Atsbi Wonberta" },
		{ value: "ganta-afeshum", label: "Ganta Afeshum" },
		{ value: "saesi-tsaedaemba", label: "Saesi Tsaedaemba" },
	],
	"southern-tigray": [
		{ value: "alamata", label: "Alamata" },
		{ value: "maychew", label: "Maychew" },
		{ value: "endamekoni", label: "Endamekoni" },
		{ value: "ofla", label: "Ofla" },
		{ value: "raya-azebo", label: "Raya Azebo" },
		{ value: "hintalo-wajirat", label: "Hintalo Wajirat" },
	],
	hawassa: [
		{ value: "hawassa-01", label: "Tabor" },
		{ value: "hawassa-02", label: "Misrak" },
		{ value: "hawassa-03", label: "Haik Dar" },
		{ value: "hawassa-04", label: "Menaharia" },
		{ value: "hawassa-05", label: "Bahil Adarash" },
		{ value: "hawassa-06", label: "Addis Ketema" },
		{ value: "hawassa-07", label: "Tula" },
		{ value: "hawassa-08", label: "Chefe Jebdu" },
	],
	jigjiga: [
		{ value: "jigjiga-01", label: "Kebele 01" },
		{ value: "jigjiga-02", label: "Kebele 02" },
		{ value: "jigjiga-03", label: "Kebele 03" },
		{ value: "jigjiga-04", label: "Kebele 04" },
		{ value: "jigjiga-05", label: "Kebele 05" },
	],
	semera: [
		{ value: "semera-01", label: "Kebele 01" },
		{ value: "semera-02", label: "Kebele 02" },
		{ value: "semera-03", label: "Kebele 03" },
	],
	"gambela-city": [
		{ value: "gambela-01", label: "Kebele 01" },
		{ value: "gambela-02", label: "Kebele 02" },
		{ value: "gambela-03", label: "Kebele 03" },
	],
	assosa: [
		{ value: "assosa-01", label: "Kebele 01" },
		{ value: "assosa-02", label: "Kebele 02" },
		{ value: "assosa-03", label: "Kebele 03" },
	],
	"dire-dawa-city": [
		{ value: "kebele-01", label: "Kebele 01" },
		{ value: "kebele-02", label: "Kebele 02" },
		{ value: "kebele-03", label: "Kebele 03" },
		{ value: "kebele-04", label: "Kebele 04" },
		{ value: "kebele-05", label: "Kebele 05" },
		{ value: "kebele-06", label: "Kebele 06" },
		{ value: "sabian", label: "Sabian" },
		{ value: "kezira", label: "Kezira" },
		{ value: "gendekore", label: "Gendekore" },
	],
	"harar-city": [
		{ value: "harar-01", label: "Abadir" },
		{ value: "harar-02", label: "Amir Nur" },
		{ value: "harar-03", label: "Jenela" },
		{ value: "harar-04", label: "Shenkor" },
		{ value: "harar-05", label: "Erer" },
		{ value: "harar-06", label: "Hakim" },
	],
} as const;

export const ETHNICITY_OPTIONS = [
	{ value: "oromo", label: "Oromo" },
	{ value: "amhara", label: "Amhara" },
	{ value: "tigray", label: "Tigray" },
	{ value: "somali", label: "Somali" },
	{ value: "sidama", label: "Sidama" },
	{ value: "gurage", label: "Gurage" },
	{ value: "wolaita", label: "Wolaita" },
	{ value: "afar", label: "Afar" },
	{ value: "hadiya", label: "Hadiya" },
	{ value: "gamo", label: "Gamo" },
	{ value: "other", label: "Other" },
] as const;
