export const EMPLOYEE_TYPES = {
	MILITARY: "MILITARY",
	CIVILIAN: "CIVILIAN",
	TEMPORARY: "TEMPORARY",
} as const;

export const EMPLOYEE_STATUSES = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
	ON_LEAVE: "ON_LEAVE",
	SUSPENDED: "SUSPENDED",
	RETIRED: "RETIRED",
	TERMINATED: "TERMINATED",
	DECEASED: "DECEASED",
} as const;
