export const SYSTEM_ROLES = {
	IT_ADMIN: "IT_ADMIN",
	HQ_ADMIN: "HQ_ADMIN",
	HR_DIRECTOR: "HR_DIRECTOR",
	CENTER_ADMIN: "CENTER_ADMIN",
	CENTER_COMMANDER: "CENTER_COMMANDER",
	HR_OFFICER: "HR_OFFICER",
	DEPARTMENT_HEAD: "DEPARTMENT_HEAD",
	SUPERVISOR: "SUPERVISOR",
	FINANCE_OFFICER: "FINANCE_OFFICER",
	RECORDS_OFFICER: "RECORDS_OFFICER",
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const ROLE_LEVELS = {
	[SYSTEM_ROLES.IT_ADMIN]: 100,
	[SYSTEM_ROLES.HQ_ADMIN]: 95,
	[SYSTEM_ROLES.HR_DIRECTOR]: 90,
	[SYSTEM_ROLES.CENTER_ADMIN]: 85,
	[SYSTEM_ROLES.CENTER_COMMANDER]: 80,
	[SYSTEM_ROLES.HR_OFFICER]: 70,
	[SYSTEM_ROLES.DEPARTMENT_HEAD]: 60,
	[SYSTEM_ROLES.SUPERVISOR]: 50,
	[SYSTEM_ROLES.FINANCE_OFFICER]: 40,
	[SYSTEM_ROLES.RECORDS_OFFICER]: 30,
} as const;

export const ACCESS_SCOPES = {
	ALL_CENTERS: "ALL_CENTERS",
	OWN_CENTER: "OWN_CENTER",
} as const;

export type AccessScope = (typeof ACCESS_SCOPES)[keyof typeof ACCESS_SCOPES];

export const HQ_ROLES = [SYSTEM_ROLES.IT_ADMIN, SYSTEM_ROLES.HQ_ADMIN, SYSTEM_ROLES.HR_DIRECTOR] as const;

export const CENTER_ROLES = [
	SYSTEM_ROLES.CENTER_ADMIN,
	SYSTEM_ROLES.CENTER_COMMANDER,
	SYSTEM_ROLES.HR_OFFICER,
	SYSTEM_ROLES.DEPARTMENT_HEAD,
	SYSTEM_ROLES.SUPERVISOR,
	SYSTEM_ROLES.FINANCE_OFFICER,
	SYSTEM_ROLES.RECORDS_OFFICER,
] as const;

export const isHqRole = (roleCode: string): boolean => {
	return (HQ_ROLES as readonly string[]).includes(roleCode);
};

export const isCenterRole = (roleCode: string): boolean => {
	return (CENTER_ROLES as readonly string[]).includes(roleCode);
};
