export const SYSTEM_ROLES = {
	IT_ADMIN: "IT_ADMIN",
	HR_DIRECTOR: "HR_DIRECTOR",
	HR_OFFICER: "HR_OFFICER",
	CENTER_COMMANDER: "CENTER_COMMANDER",
	DEPARTMENT_HEAD: "DEPARTMENT_HEAD",
	SUPERVISOR: "SUPERVISOR",
	FINANCE_OFFICER: "FINANCE_OFFICER",
	RECORDS_OFFICER: "RECORDS_OFFICER",
	VIEWER: "VIEWER",
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const ROLE_LEVELS = {
	[SYSTEM_ROLES.IT_ADMIN]: 100,
	[SYSTEM_ROLES.HR_DIRECTOR]: 90,
	[SYSTEM_ROLES.CENTER_COMMANDER]: 80,
	[SYSTEM_ROLES.HR_OFFICER]: 70,
	[SYSTEM_ROLES.DEPARTMENT_HEAD]: 60,
	[SYSTEM_ROLES.SUPERVISOR]: 50,
	[SYSTEM_ROLES.FINANCE_OFFICER]: 40,
	[SYSTEM_ROLES.RECORDS_OFFICER]: 30,
	[SYSTEM_ROLES.VIEWER]: 10,
} as const;

export const ACCESS_SCOPES = {
	ALL_CENTERS: "ALL_CENTERS",
	OWN_CENTER: "OWN_CENTER",
	OWN_DEPARTMENT: "OWN_DEPARTMENT",
	OWN_RECORDS: "OWN_RECORDS",
} as const;

export type AccessScope = (typeof ACCESS_SCOPES)[keyof typeof ACCESS_SCOPES];
